#!/usr/bin/env python3

import tkinter as tk
from tkinter import messagebox

COLORS = [
    ("Black", "#000000"),
    ("White", "#ffffff"),
    ("Red", "#ff0000"),
    ("Green", "#00ff00"),
    ("Blue", "#0000ff"),
    ("Gray", "#808080"),
]

index = 0

root = tk.Tk()
root.withdraw()

messagebox.showinfo(
    "Screen / Dead Pixel Test",
    "The display will switch to fullscreen solid colors.\n\n"
    "Use Left / Right or Space to change colors.\n"
    "Click the screen to advance.\n"
    "Press Esc to exit.\n\n"
    "Look for dead pixels, stuck pixels, uneven brightness, "
    "discoloration, flickering or other visible defects.",
)

root.deiconify()
root.attributes("-fullscreen", True)
root.configure(cursor="none")

canvas = tk.Canvas(
    root,
    highlightthickness=0,
    borderwidth=0,
)
canvas.pack(fill="both", expand=True)


def show_color():
    _, color = COLORS[index]
    canvas.configure(background=color)


def next_color(event=None):
    global index
    index = (index + 1) % len(COLORS)
    show_color()


def previous_color(event=None):
    global index
    index = (index - 1) % len(COLORS)
    show_color()


root.bind("<Escape>", lambda event: root.destroy())
root.bind("<Right>", next_color)
root.bind("<space>", next_color)
root.bind("<Left>", previous_color)
root.bind("<Button-1>", next_color)

show_color()
root.mainloop()
